prose:
  metadata:
    _posts:
      - name: "categories"
        field:
          element: "hidden"
          value:
            - "post"
      - name: "layout"
        field:
          element: "text"
          label: "Layout"
          value: "default"
      - name: "item"
        field:
          element: "select"
          label: "Item"
          placeholder: "Select an Item"
          options:
            - name: "Item 1"
              value: "item1"
            - name: "Item 2"
              value: "item2"
          selected: "item2"