auto: true
server: true
pygments: true
permalink: none
baseurl: ""
oauth_client_id: 9dd68bf1f97f8318f804
gatekeeper_url: http://gatekeeper.twcenter.mx
exclude:
- .gitignore
- README.md

prose:
        rooturl: "_posts"
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "posts"
      - name: "categories"
        field:
          element: "select"
          label: "Categoria"
          placeholder: "Selecciona una Categor'ia"
          options:
          - name: "Ciencia y Tecnología"
          value: "Ciencia y Tecnología"

          - name: "Cultura y Espectáculos"
          value: "Cultura y Espectáculos"

          - name: "Opinión"
          value: "Opinión"

          - name: "Educación"
          value: "Educación"

          - name: "Sociedad y Justicia"
          value: "Sociedad y Justicia"

          - name: "Contraportada"
          value: "Contraportada"

          - name: "Deportes"
          value: "Deportes"

          - name: "Política"
          value: "Política"

          - name: "Economía"
          value: "Economía"

          - name: "Mundo"
          value: "Mundo"

          - name: "Municipios"
          value: "Municipios"

          - name: "Reportaje Especial"
          value: "Reportaje Especial"

          - name: "De Rock"
          value: "De Rock"

          - name: "La Jiribilla"
          value: "La Jiribilla"

          - name: "Fuera de Foco"
          value: "Fuera de Foco"

          - name: "Cartones"
          value: "Cartones"

          - name: "Principales"
          value: "Principales"

          - name: "A debate"
          value: "A debate"

          - name: "Zacatecas"
          value: "Zacatecas"

          - name: "México"
          value: "México"

          - name: "Destacadas"
          value: "Destacadas"

          - name: "Autor"
          value: "Autor"

          - name: "Publicidad"
          value: "Publicidad"

          - name: "Editorial"
          value: "Editorial"

          selected: "item2"